### ISSUE TITLE
Engines >= 18?

### ISSUE THREAD

**Issue by JeffJassky** [microlinkhq/tinyspawn#7]
## Question
The package.json shows that it's designed for node versions >= 18. After reviewing the codebase of tinyspawn I did not notice any specific features that would inherently require Node.js version 18 or higher.

Is there a genuine reason this package is not designed for lower versions of node, like 12, or 14?

## Downstream Impact
If tinyspawn can be compatible with lower versions of Node.js (particularly >=14), it would be beneficial for downstream dependencies that target a broader range of Node.js versions, like the youtube-dl-exec package.

## Suggestion
If tinyspawn is indeed compatible with lower Node.js versions (like >=14), the engines field in package.json could be updated.

**Comment by Kikobeats** [comment]
it can probably for versions older than Node.js v18, but since CI tests aren't running against old version, I prefer to be conservative 🙂
